# Generated by Django 3.2.6 on 2021-09-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=models.CharField(max_length=400),
        ),
    ]
