# Generated by Django 3.2.6 on 2021-09-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_role_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.CharField(max_length=80),
        ),
    ]
